/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrasilguardRouteImport } from './routes/brasilguard'
import { Route as CanaisRouteImport } from './routes/canais'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProvedoresRouteImport } from './routes/provedores'
import { Route as RastreioRouteImport } from './routes/rastreio'
import { Route as SalaRouteImport } from './routes/sala'
import { Route as TentaculosRouteImport } from './routes/tentaculos'
import { Route as AgenteIdRouteImport } from './routes/agente.$id'
import { Route as InboxIdRouteImport } from './routes/inbox.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrasilguardRoute = BrasilguardRouteImport.update({
  id: '/brasilguard',
  path: '/brasilguard',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaisRoute = CanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvedoresRoute = ProvedoresRouteImport.update({
  id: '/provedores',
  path: '/provedores',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioRoute = RastreioRouteImport.update({
  id: '/rastreio',
  path: '/rastreio',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaRoute = SalaRouteImport.update({
  id: '/sala',
  path: '/sala',
  getParentRoute: () => rootRouteImport,
} as any)
const TentaculosRoute = TentaculosRouteImport.update({
  id: '/tentaculos',
  path: '/tentaculos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenteIdRoute = AgenteIdRouteImport.update({
  id: '/agente/$id',
  path: '/agente/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIdRoute = InboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InboxRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brasilguard': typeof BrasilguardRoute
  '/canais': typeof CanaisRoute
  '/crm': typeof CrmRoute
  '/equipe': typeof EquipeRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/provedores': typeof ProvedoresRoute
  '/rastreio': typeof RastreioRoute
  '/sala': typeof SalaRoute
  '/tentaculos': typeof TentaculosRoute
  '/agente/$id': typeof AgenteIdRoute
  '/inbox/$id': typeof InboxIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brasilguard': typeof BrasilguardRoute
  '/canais': typeof CanaisRoute
  '/crm': typeof CrmRoute
  '/equipe': typeof EquipeRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/provedores': typeof ProvedoresRoute
  '/rastreio': typeof RastreioRoute
  '/sala': typeof SalaRoute
  '/tentaculos': typeof TentaculosRoute
  '/agente/$id': typeof AgenteIdRoute
  '/inbox/$id': typeof InboxIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brasilguard': typeof BrasilguardRoute
  '/canais': typeof CanaisRoute
  '/crm': typeof CrmRoute
  '/equipe': typeof EquipeRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/provedores': typeof ProvedoresRoute
  '/rastreio': typeof RastreioRoute
  '/sala': typeof SalaRoute
  '/tentaculos': typeof TentaculosRoute
  '/agente/$id': typeof AgenteIdRoute
  '/inbox/$id': typeof InboxIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/brasilguard'
    | '/canais'
    | '/crm'
    | '/equipe'
    | '/inbox'
    | '/login'
    | '/provedores'
    | '/rastreio'
    | '/sala'
    | '/tentaculos'
    | '/agente/$id'
    | '/inbox/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/brasilguard'
    | '/canais'
    | '/crm'
    | '/equipe'
    | '/inbox'
    | '/login'
    | '/provedores'
    | '/rastreio'
    | '/sala'
    | '/tentaculos'
    | '/agente/$id'
    | '/inbox/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/brasilguard'
    | '/canais'
    | '/crm'
    | '/equipe'
    | '/inbox'
    | '/login'
    | '/provedores'
    | '/rastreio'
    | '/sala'
    | '/tentaculos'
    | '/agente/$id'
    | '/inbox/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BrasilguardRoute: typeof BrasilguardRoute
  CanaisRoute: typeof CanaisRoute
  CrmRoute: typeof CrmRoute
  EquipeRoute: typeof EquipeRoute
  InboxRoute: typeof InboxRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProvedoresRoute: typeof ProvedoresRoute
  RastreioRoute: typeof RastreioRoute
  SalaRoute: typeof SalaRoute
  TentaculosRoute: typeof TentaculosRoute
  AgenteIdRoute: typeof AgenteIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brasilguard': {
      id: '/brasilguard'
      path: '/brasilguard'
      fullPath: '/brasilguard'
      preLoaderRoute: typeof BrasilguardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canais': {
      id: '/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof CanaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provedores': {
      id: '/provedores'
      path: '/provedores'
      fullPath: '/provedores'
      preLoaderRoute: typeof ProvedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio': {
      id: '/rastreio'
      path: '/rastreio'
      fullPath: '/rastreio'
      preLoaderRoute: typeof RastreioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sala': {
      id: '/sala'
      path: '/sala'
      fullPath: '/sala'
      preLoaderRoute: typeof SalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentaculos': {
      id: '/tentaculos'
      path: '/tentaculos'
      fullPath: '/tentaculos'
      preLoaderRoute: typeof TentaculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agente/$id': {
      id: '/agente/$id'
      path: '/agente/$id'
      fullPath: '/agente/$id'
      preLoaderRoute: typeof AgenteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$id': {
      id: '/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof InboxIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InboxRouteChildren {
  InboxIdRoute: typeof InboxIdRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxIdRoute: InboxIdRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BrasilguardRoute: BrasilguardRoute,
  CanaisRoute: CanaisRoute,
  CrmRoute: CrmRoute,
  EquipeRoute: EquipeRoute,
  InboxRoute: InboxRouteWithChildren,
  LoginRoute: LoginRoute,
  ProvedoresRoute: ProvedoresRoute,
  RastreioRoute: RastreioRoute,
  SalaRoute: SalaRoute,
  TentaculosRoute: TentaculosRoute,
  AgenteIdRoute: AgenteIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
